name: Run My Bot
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # SHA for v4
      
      - name: Set up Python
        uses: actions/setup-python@0b93645e5efa731d7a3e30f1469736561168925e # SHA for v5
        with:
          python-version: '3.9'
          
      - name: Run bot.py
        run: python bot.py
        
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "تحديث تلقائي من البوت" || echo "لا توجد تغييرات"
          git push
          
